const ProjectDatas = {
  project1: {
    title: "가챠카챠",
    image: "/img/portfolio/1.png",
    content: "쇼핑몰 관리자페이지",
    badge: "학원",
    badgeColor: "#2196F3",
    gitUrls: [
      { type: "Github", url: "https://github.com/jolennon77/gachakacha" },
    ],
    pptUrl: "https://www.canva.com/design/DAGJZBQjcrI/qXO3Sp5Qsw2z05D8ZC-aEg/edit?utm_content=DAGJZBQjcrI&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton",
    detailedContent: "쇼핑몰 관리자페이지에 대한 상세 내용입니다.",
    role: "혼자함",
    backend: ["Java"],
    db: ["MySQL"],
    frontend: ["HTML5", "JavaScript", "Jquery", "CSS"],
    server: ["Apachetomcat"],
    tool: ["Eclipse"],
    collaborations: ["Notion","Git"],
    duration: "1 months",
    team: "4 members",
    youtube: "https://www.youtube.com/embed/56BqfOY2Cj4?si=JteZbwQProHRTajT"
  },
  project2: {
    title: "레트로 플래닛",
    image: "/img/portfolio/2.png",
    content: "레트로 컨셉 SNS",
    badge: "개인",
    badgeColor: "#FF9800",
    gitUrls: [
      { type: "Github", url: "https://github.com/jolennon77/RetroPlanet" },
    ],
    pptUrl: " ",
    detailedContent: "레트로 컨셉의 SNS에 대한 상세 내용입니다.",
    role: "혼자함",
    backend: ["Java", "SpringBoot"],
    db: ["MySQL"],
    frontend: ["HTML5", "JavaScript", "Jquery", "CSS"],
    server: ["Apachetomcat"],
    tool: ["VSC","IntelliJ"],
    collaborations: ["Git"],
    duration: "1 months",
    team: "1 members",
    youtube: "https://www.youtube.com/embed/11cta61wi0g?si=4-Gj0rFj3zXy4Su-"
  },
  project3: {
    title: "룩복",
    image: "/img/portfolio/3.png",
    content: "날씨기반 의상추천",
    badge: "개인",
    badgeColor: "#FF9800",
    gitUrls: [
      { type: "Github_Frontend", url: "https://github.com/jolennon77/lookbok" },
      { type: "Github_Backend", url: "https://github.com/jolennon77/lookbok_be" }
    ],
    pptUrl: " ",
    detailedContent: "날씨기반 의상추천에 대한 상세 내용입니다.",
    role: "혼자함",
    backend: ["Java", "SpringBoot"],
    db: ["MySQL"],
    frontend: ["React", "HTML5", "JavaScript", "CSS"],
    server: ["Apachetomcat"],
    tool: ["VSC","IntelliJ","Postman"],
    collaborations: ["Notion","Git"],
    duration: "1 months",
    team: "1 members",
    youtube: "https://www.youtube.com/embed/11cta61wi0g?si=4-Gj0rFj3zXy4Su-"
  },
  project4: {
    title: "야숨",
    image: "/img/portfolio/4.png",
    content: "날씨기반 캠핑장추천",
    badge: "학원",
    badgeColor: "#2196F3",
    gitUrls: [
      { type: "Frontend", url: "https://github.com/Breath-of-the-Wild/Breath-of-the-Wild_fe" },
      { type: "Backend", url: "https://github.com/Breath-of-the-Wild/Breath-of-the-Wild_be" }
    ],
    pptUrl: "https://www.canva.com/design/DAGJZPETgig/WZGfqW5tCFW3J3rApbvE5A/edit?utm_content=DAGJZPETgig&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton",
    detailedContent: "날씨기반 캠핑장추천에 대한 상세 내용입니다.",
    role: "이것저것함",
    backend: ["Java", "SpringBoot"],
    db: ["MySQL"],
    frontend: ["React", "HTML5", "JavaScript", "CSS"],
    server: ["Apachetomcat","AWS","Docker"],
    tool: ["VSC","IntelliJ","Postman"],
    collaborations: ["Notion","Git"],
    duration: "1 months",
    team: "5 members",
    youtube: "https://www.youtube.com/embed/OV2fwlyAgrQ?si=tzm7h87jP6TbC3TV"
  },
  project5: {
    title: "개인 홈페이지",
    image: "/img/portfolio/5.png",
    content: "개인 홈페이지",
    badge: "개인",
    badgeColor: "#FF9800",
    gitUrls: [
      { type: "Github", url: "https://github.com/jolennon77/jolennon77.github.io" },
    ],
    pptUrl: " ",
    detailedContent: "개인 홈페이지에 대한 상세 내용입니다.",
    role: "혼자함",
    backend: [],
    db: [],
    frontend: ["React", "HTML5", "JavaScript", "CSS"],
    server: [ ],
    tool: ["VSC"],
    collaborations: ["Git"],
    duration: "1 month",
    team: "1 member",
    youtube: "https://www.youtube.com/embed/11cta61wi0g?si=4-Gj0rFj3zXy4Su-"
  },
  project6: {
    title: "슬리슬리",
    image: "/img/portfolio/6.png",
    content: "WebRTC 활용 웹어플리케이션",
    badge: "학원",
    badgeColor: "#2196F3",
    gitUrls: [
      { type: "Frontend", url: "https://github.com/dmsp0/slisli_frontend" },
      { type: "Backend", url: "https://github.com/dmsp0/slisli_backend" }
    ],
    pptUrl: "https://www.canva.com/design/DAGJZD3jMSg/Q4HEFK8bACj2kFVlNzljMg/edit?utm_content=DAGJZD3jMSg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton",
    detailedContent: "4차 프로젝트에 대한 상세 내용입니다.",
    role: "이것저것함",
    backend: ["Java", "SpringBoot"],
    db: ["MySQL"],
    frontend: ["React", "HTML5", "JavaScript", "CSS"],
    server: ["Nginx","AWS","Docker"],
    tool: ["VSC","IntelliJ","Postman"],
    collaborations: ["Notion","Git"],
    duration: "1 months",
    team: "5 members",
    youtube: "https://www.youtube.com/embed/IWkERpy9uFo?si=M1d8kDSh8WcSOclP"
  },
};

export default ProjectDatas;
